import { Jockey_One, Noto_Serif_Balinese } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import ThemeToggle from "../components/ThemeToggle";
import Lottie from "lottie-react";



const jockeyOne = Jockey_One({
  variable: "--font-jockey-one",
  subsets: ["latin"],
  weight: "400",
});

const notoSerifBalinese = Noto_Serif_Balinese({
  variable: "--font-noto-serif-balinese",
  subsets: ["latin"],
  weight: "400",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${jockeyOne.variable} ${notoSerifBalinese.variable} antialiased`}
      >
        <Providers>
          
          <div className="absolute top-4 right-4">
            <ThemeToggle />
          </div>
          {children}
        </Providers>
      </body>
    </html>
  );
}
